// Autogenerated by - D:/home/lugansky-igor/in-the-vicinity-cc/embedded_script_engines/tools/first_level_wrapper.py

//#include "app/config.h"  // TODO: Need impl.
#include "forge_v8_point.h"  // TODO: Need connect real.

// C++
#include <string>

using std::string;

using v8::Object;
using v8::Handle;
using v8::Local;
using v8::Value;
using v8::ObjectTemplate;
using v8::External;
using v8::Context;
using v8::Isolate;
using v8::Persistent;
using v8::Integer;
using v8::String;


void ForgeV8unknowns::v8_getter_lengthAllParams___(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info) 
  {
  Local<Object> self = info.Holder();
  Local<External> wrap = Local<External>::Cast(self->GetInternalField(0));
  void* ptr = wrap->Value();
  int value = static_cast<unknown*>(ptr)->lengthAllParams___;
  info.GetReturnValue().Set(Integer::New(value));
}

void ForgeV8unknowns::v8_getter_counterDebug___(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info) 
  {
  Local<Object> self = info.Holder();
  Local<External> wrap = Local<External>::Cast(self->GetInternalField(0));
  void* ptr = wrap->Value();
  int value = static_cast<unknown*>(ptr)->counterDebug___;
  info.GetReturnValue().Set(Integer::New(value));
}

void ForgeV8unknowns::v8_getter_typeControl_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info) 
  {
  Local<Object> self = info.Holder();
  Local<External> wrap = Local<External>::Cast(self->GetInternalField(0));
  void* ptr = wrap->Value();
  std::string value = static_cast<unknown*>(ptr)->typeControl_;
  info.GetReturnValue().Set(String::New(value));
}

void ForgeV8unknowns::v8_getter_currentQueryIndex_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info) 
  {
  Local<Object> self = info.Holder();
  Local<External> wrap = Local<External>::Cast(self->GetInternalField(0));
  void* ptr = wrap->Value();
  int value = static_cast<unknown*>(ptr)->currentQueryIndex_;
  info.GetReturnValue().Set(Integer::New(value));
}
