// Autogenerated by - D:/home/lugansky-igor/github/in-the-vicinity-cc/embedded_script_engines/tools/tests_medium/first_level_gen_test.py
#ifndef FORGEV8UNKNOWNS_H_
#define FORGEV8UNKNOWNS_H_

// Other
#include <v8.h>

#include "point.h"

//StateLess
class ForgeV8unknowns {
 public:
  ForgeV8unknowns() { }

  // TODO: It need be impl. manual
  v8::Handle<v8::Object> Forge_NI(
      Point* point, 
      v8::Isolate* isolate,
      v8::Persistent<v8::ObjectTemplate>* blueprint);

  // TODO: It need be impl. manual
  v8::Handle<v8::ObjectTemplate> MakeBlueprint_NI(v8::Isolate* isolate);

  static void ForgeV8unknowns::v8_getter_lengthAllParams___(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_counterDebug___(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_typeControl_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_failsReseted_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_currentQueryIndex_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_powerOkTTgr_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_needPrintFullPower_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_needPrintOkPower_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_FRWOkTTgr_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_needPrintFullFRW_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_needPrintOkFRW_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_iChannel(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_iChannelSetup(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_realPowerRepresent___(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_FRWValue___(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_iBallastPower(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_transmitterAddress___(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_iMaxTemre(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_iMaxStatus(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_new_max_temperature_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_iNewMaxStatus(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_connecton_state___(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_snmp_connecton_status___(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_transmitter_number_to_set_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_hasMsgForSnmp_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_statusRecordIndex_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_newFailOccure_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_FRWOk_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_temperatureWasOk_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_counterFailsAndWarns_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_iUsedTime(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_iUsedReserv(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_lengthCfgAnswer(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_nominalPower___(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8unknowns::v8_getter_excitersTotal_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

};
#endif