// Autogenerated by - D:\home\lugansky-igor\github\in-the-vicinity-cc\embedded_script_engines\tools\app_first_level_gen.py
#ifndef FORGEV8DATABASES_H_
#define FORGEV8DATABASES_H_

// Other
#include <v8.h>

#include "point.h"

//StateLess
class ForgeV8DataBases {
 public:
  ForgeV8DataBases() { }

  // TODO: It need be impl. manual
  v8::Handle<v8::Object> Forge_NI(
      Point* point, 
      v8::Isolate* isolate,
      v8::Persistent<v8::ObjectTemplate>* blueprint);

  // TODO: It need be impl. manual
  v8::Handle<v8::ObjectTemplate> MakeBlueprint_NI(v8::Isolate* isolate);

  static void ForgeV8DataBases::v8_getter_lengthAllParams___(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8DataBases::v8_getter_counterDebug___(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8DataBases::v8_getter_typeControl_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8DataBases::v8_getter_failsReseted_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

  static void ForgeV8DataBases::v8_getter_currentQueryIndex_(
    v8::Local<v8::String> name,
    const v8::PropertyCallbackInfo<v8::Value>& info);

};
#endif